//! Public library entrypoints for the `gpx` CLI.
//!
//! This module exposes the command-line parser and dispatch so external
//! callers (for example Python bindings) can invoke `gpx` behavior.

pub mod commands;
pub mod io;
pub mod services;

use anyhow::Result;
use clap::{Parser, Subcommand, ValueEnum};
use egobox_moe::{CorrelationSpec, RegressionSpec};

use crate::commands::{run_fit, run_predict, run_py, run_qa, run_spec};

#[derive(Parser)]
#[command(author, version, about, long_about = None)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Commands,
}

#[derive(Copy, Clone, Debug, ValueEnum)]
pub enum ModelFormat {
    Json,
    Binary,
}

#[derive(Copy, Clone, Debug, ValueEnum)]
pub enum DataFormat {
    Csv,
    Npy,
}

#[derive(Copy, Clone, Debug, ValueEnum)]
pub enum RegressionChoice {
    Constant,
    Linear,
    Quadratic,
    All,
}

impl From<RegressionChoice> for RegressionSpec {
    fn from(value: RegressionChoice) -> Self {
        match value {
            RegressionChoice::Constant => RegressionSpec::CONSTANT,
            RegressionChoice::Linear => RegressionSpec::LINEAR,
            RegressionChoice::Quadratic => RegressionSpec::QUADRATIC,
            RegressionChoice::All => RegressionSpec::ALL,
        }
    }
}

#[derive(Copy, Clone, Debug, ValueEnum)]
pub enum CorrelationChoice {
    SquaredExponential,
    AbsoluteExponential,
    Matern32,
    Matern52,
    All,
}

impl From<CorrelationChoice> for CorrelationSpec {
    fn from(value: CorrelationChoice) -> Self {
        match value {
            CorrelationChoice::SquaredExponential => CorrelationSpec::SQUAREDEXPONENTIAL,
            CorrelationChoice::AbsoluteExponential => CorrelationSpec::ABSOLUTEEXPONENTIAL,
            CorrelationChoice::Matern32 => CorrelationSpec::MATERN32,
            CorrelationChoice::Matern52 => CorrelationSpec::MATERN52,
            CorrelationChoice::All => CorrelationSpec::ALL,
        }
    }
}

#[derive(Copy, Clone, Debug, ValueEnum)]
pub enum RecombinationChoice {
    Hard,
    Smooth,
}

#[derive(Subcommand)]
pub enum Commands {
    /// Fit GP surrogates from tabular data
    Fit {
        /// Training input file
        input: String,

        /// Number of output columns taken from the end of each training row
        #[arg(long, default_value_t = 1)]
        outputs: usize,

        /// Regression model specification used when fitting each surrogate
        #[arg(long, value_enum, default_value_t = RegressionChoice::Constant)]
        regression_spec: RegressionChoice,

        /// Correlation model specification used when fitting each surrogate
        #[arg(long, value_enum, default_value_t = CorrelationChoice::SquaredExponential)]
        correlation_spec: CorrelationChoice,

        /// Optional number of PLS components for KPLS dimension reduction
        #[arg(long)]
        kpls_dim: Option<usize>,

        /// Number of clusters (number of local experts)
        #[arg(long, default_value_t = 1)]
        n_clusters: usize,

        /// Recombination mode used to combine experts
        #[arg(long, value_enum, default_value_t = RecombinationChoice::Smooth)]
        recombination: RecombinationChoice,

        /// Optional smooth recombination factor (used only when recombination is smooth)
        #[arg(long)]
        smooth_factor: Option<f64>,

        /// Output model file path
        #[arg(short, long, default_value = "surrogate_model.gpx")]
        output: String,
    },
    /// Assess quality metrics of one or several GP models
    Qa {
        /// GP file generated by Egor optimizer or Gpx save
        #[arg(long, default_value = "surrogate_model.gpx")]
        model: String,

        /// Optional model index to assess a single surrogate; if omitted, all models are used
        #[arg(short = 'm', long)]
        model_index: Option<usize>,

        /// Use K folding cross validation procedure (default LOO)
        #[arg(short, long, default_value_t = 0)]
        kfold: usize,
    },
    /// Display GP model input/output specifications
    Spec {
        /// GP file generated by Egor optimizer or Gpx save
        #[arg(long, default_value = "surrogate_model.gpx")]
        model: String,

        /// Optional model index to inspect a single surrogate; if omitted, all models are shown
        #[arg(short = 'm', long)]
        model_index: Option<usize>,
    },
    /// Predict outputs for tabular input samples
    Predict {
        /// Input file containing one sample per row
        input: String,

        /// GP file generated by Egor optimizer or Gpx save
        #[arg(long, default_value = "surrogate_model.gpx")]
        model: String,

        /// Output file where predictions are written
        #[arg(short, long, default_value = "surrogate_predictions.csv")]
        output: String,

        /// Include predictive variance in output data
        #[arg(long, default_value_t = false)]
        with_variance: bool,

        /// Optional model index to predict a single output; if omitted, all models are used
        #[arg(short = 'm', long)]
        model_index: Option<usize>,
    },
    /// Generate a Python helper script with an inlined GP model
    Py {
        /// GP file generated by Egor optimizer or Gpx save
        #[arg(long, default_value = "surrogate_model.gpx")]
        model: String,

        /// Output Python script file path
        #[arg(short, long, default_value = "gpx.py")]
        output: String,
    },
}

pub fn run_from_iter<I, T>(args: I) -> Result<()>
where
    I: IntoIterator<Item = T>,
    T: Into<std::ffi::OsString> + Clone,
{
    let cli = Cli::try_parse_from(args).map_err(|e| anyhow::anyhow!(e.to_string()))?;
    run_cli(cli)
}

pub fn run_from_iter_with_exit_code<I, T>(args: I) -> i32
where
    I: IntoIterator<Item = T>,
    T: Into<std::ffi::OsString> + Clone,
{
    match Cli::try_parse_from(args) {
        Ok(cli) => match run_cli(cli) {
            Ok(()) => 0,
            Err(err) => {
                eprintln!("{err}");
                1
            }
        },
        Err(err) => {
            let code = match err.kind() {
                clap::error::ErrorKind::DisplayHelp | clap::error::ErrorKind::DisplayVersion => 0,
                _ => 2,
            };
            let _ = err.print();
            code
        }
    }
}

pub fn run() -> Result<()> {
    run_cli(Cli::parse())
}

fn run_cli(cli: Cli) -> Result<()> {
    match cli.command {
        Commands::Fit {
            input,
            outputs,
            regression_spec,
            correlation_spec,
            kpls_dim,
            n_clusters,
            recombination,
            smooth_factor,
            output,
        } => run_fit(
            &input,
            outputs,
            regression_spec,
            correlation_spec,
            kpls_dim,
            n_clusters,
            recombination,
            smooth_factor,
            &output,
        ),
        Commands::Qa {
            model,
            model_index,
            kfold,
        } => run_qa(&model, model_index, kfold),
        Commands::Spec { model, model_index } => run_spec(&model, model_index),
        Commands::Predict {
            input,
            model,
            output,
            with_variance,
            model_index,
        } => run_predict(&model, &input, &output, with_variance, model_index),
        Commands::Py { model, output } => run_py(&model, &output),
    }
}
