use anyhow::{Context, Result, anyhow, bail};
use clap::{Parser, Subcommand, ValueEnum};
use egobox_moe::GpMetric;
use egobox_moe::GpMixture;
use egobox_moe::GpSurrogate;
use egobox_moe::MixtureGpSurrogate;
use linfa::Dataset;
use linfa::traits::Fit;
use ndarray::{Array1, Array2};
use ndarray_npy::{read_npy, write_npy};
use rayon::prelude::*;
use std::collections::HashMap;
use std::fs;

#[derive(Parser)]
#[command(author, version, about, long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Copy, Clone, Debug, ValueEnum)]
enum ModelFormat {
    Json,
    Binary,
}

#[derive(Copy, Clone, Debug, ValueEnum)]
enum DataFormat {
    Csv,
    Npy,
}

#[derive(Subcommand)]
enum Commands {
    /// Fit a default GP surrogate from tabular data
    Fit {
        /// Training input file
        #[arg(short, long)]
        input: String,

        /// Training input data format
        #[arg(long, value_enum, default_value_t = DataFormat::Csv)]
        input_format: DataFormat,

        /// Output model file path
        #[arg(short, long)]
        output: String,

        /// Model output format
        #[arg(long, value_enum, default_value_t = ModelFormat::Binary)]
        format: ModelFormat,
    },
    /// Assess quality metrics of one or several GP models
    Qa {
        /// Binary GP file generated by Egor optimizer or Gpx save
        model: String,

        /// Use K folding cross validation procedure (default LOO)
        #[arg(short, long, default_value_t = 0)]
        kfold: usize,
    },
    /// Display model input/output specification
    Spec {
        /// Binary GP file generated by Egor optimizer or Gpx save
        model: String,

        /// Index of model to inspect when file contains multiple models
        #[arg(short, long, default_value_t = 0)]
        model_index: usize,
    },
    /// Predict outputs for tabular input samples
    Predict {
        /// Binary GP file generated by Egor optimizer or Gpx save
        model: String,

        /// Input file containing one sample per row
        #[arg(short, long)]
        input: String,

        /// Input data format
        #[arg(long, value_enum, default_value_t = DataFormat::Csv)]
        input_format: DataFormat,

        /// Output file where predictions are written
        #[arg(short, long)]
        output: String,

        /// Output data format
        #[arg(long, value_enum, default_value_t = DataFormat::Csv)]
        output_format: DataFormat,

        /// Include predictive variance in output data
        #[arg(long, default_value_t = false)]
        with_variance: bool,

        /// Index of model to use when file contains multiple models
        #[arg(short, long, default_value_t = 0)]
        model_index: usize,
    },
}

#[derive(Debug, Clone)]
struct Metrics {
    pub q2: f64,
    pub pva: f64,
    pub iae_alpha: f64,
}

fn compute_metrics(gp_models: &[Box<dyn MixtureGpSurrogate>], kfold: usize) -> Vec<Metrics> {
    let mut res: Vec<_> = gp_models
        .par_iter()
        .enumerate()
        .map(|(i, gp)| {
            let scores: Vec<_> = [GpMetric::Q2, GpMetric::Pva, GpMetric::IAEAlphaWithPlot]
                .par_iter()
                .map(|m| {
                    let score = gp.as_ref().score(*m, kfold);
                    (m, score)
                })
                .collect();
            let scores: HashMap<_, _> = scores.into_iter().collect();

            if i == 0
                && let Some(data) = &scores.get(&GpMetric::IAEAlphaWithPlot).unwrap().plot_data
            {
                println!("\nIAEα plot data for first GP model:");
                println!("Alpha | Empirical coverage | Target coverage | Delta");
                println!("---------------------------------------------------");
                for i in 0..data.alphas.len() {
                    let alpha = data.alphas[i];
                    let delta = data.deltas[i];

                    println!(
                        "{:5.2}% |       {:5.2}%      |     {:5.2}%    | {:5.2}%",
                        alpha * 100.,
                        delta * 100.,
                        (1. - alpha) * 100.,
                        (delta - (1. - alpha)).abs() * 100.
                    );
                }
                println!();
            }

            (
                i,
                Metrics {
                    q2: scores.get(&GpMetric::Q2).unwrap().value,
                    pva: scores.get(&GpMetric::Pva).unwrap().value,
                    iae_alpha: scores.get(&GpMetric::IAEAlphaWithPlot).unwrap().value,
                },
            )
        })
        .collect();
    res.sort_by_key(|(i, _)| *i);
    res.into_iter().map(|(_, m)| m).collect::<Vec<_>>()
}

fn decode_binary_models(data: &[u8]) -> Result<Vec<Box<dyn MixtureGpSurrogate>>> {
    let gp_models: Vec<Box<dyn MixtureGpSurrogate>> =
        bincode::serde::decode_from_slice(data, bincode::config::standard())
            .map(|(res, _)| res)
            .unwrap_or_default();

    if !gp_models.is_empty() {
        return Ok(gp_models);
    }

    let gp: Box<GpMixture> = bincode::serde::decode_from_slice(data, bincode::config::standard())
        .map(|(res, _)| res)
        .map_err(|e| anyhow!("cannot decode binary model: {e}"))?;
    Ok(vec![gp as Box<dyn MixtureGpSurrogate>])
}

fn decode_json_models(data: &[u8]) -> Result<Vec<Box<dyn MixtureGpSurrogate>>> {
    let gp_models: Vec<Box<dyn MixtureGpSurrogate>> = serde_json::from_slice(data).unwrap_or_default();

    if !gp_models.is_empty() {
        return Ok(gp_models);
    }

    let gp: Box<GpMixture> =
        serde_json::from_slice(data).map_err(|e| anyhow!("cannot decode JSON model: {e}"))?;
    Ok(vec![gp as Box<dyn MixtureGpSurrogate>])
}

fn load_models(path: &str) -> Result<Vec<Box<dyn MixtureGpSurrogate>>> {
    let data: Vec<u8> = fs::read(path).with_context(|| format!("cannot read model file {path}"))?;

    decode_binary_models(&data)
        .or_else(|_| decode_json_models(&data))
        .map_err(|e| anyhow!("cannot decode model file {path}: {e}"))
}

fn select_model(
    gp_models: &[Box<dyn MixtureGpSurrogate>],
    model_index: usize,
) -> Result<&dyn MixtureGpSurrogate> {
    gp_models
        .get(model_index)
        .map(|m| m.as_ref())
        .ok_or_else(|| {
            anyhow!(
                "model index {} is out of range [0, {})",
                model_index,
                gp_models.len()
            )
        })
}

fn parse_csv_row(line: &str) -> Result<Vec<f64>> {
    line.split(',')
        .map(str::trim)
        .map(|cell| {
            cell.parse::<f64>()
                .map_err(|e| anyhow!("invalid float value '{cell}': {e}"))
        })
        .collect()
}

fn is_header_row(line: &str) -> bool {
    let cells: Vec<_> = line.split(',').map(str::trim).collect();
    !cells.is_empty() && cells.iter().all(|cell| cell.parse::<f64>().is_err())
}

fn read_input_csv(path: &str, nx: usize) -> Result<Array2<f64>> {
    let content =
        fs::read_to_string(path).with_context(|| format!("cannot read input CSV {path}"))?;

    let mut nrows = 0usize;
    let mut flat_values = Vec::new();
    let mut first_non_empty = true;

    for (line_index, raw_line) in content.lines().enumerate() {
        let line = raw_line.trim();
        if line.is_empty() {
            continue;
        }

        let row = match parse_csv_row(line) {
            Ok(row) => row,
            Err(_e) if first_non_empty && is_header_row(line) => {
                first_non_empty = false;
                continue;
            }
            Err(e) => {
                return Err(e)
                    .with_context(|| format!("invalid CSV row at line {}", line_index + 1));
            }
        };
        first_non_empty = false;

        if row.len() != nx {
            bail!(
                "invalid input dimension at line {}: expected {} values, got {}",
                line_index + 1,
                nx,
                row.len()
            );
        }

        flat_values.extend(row);
        nrows += 1;
    }

    if nrows == 0 {
        bail!("input CSV {path} does not contain any sample row");
    }

    Array2::from_shape_vec((nrows, nx), flat_values)
        .map_err(|e| anyhow!("cannot build input matrix from CSV {path}: {e}"))
}

fn read_input_npy(path: &str, nx: usize) -> Result<Array2<f64>> {
    let x: Array2<f64> =
        read_npy(path).with_context(|| format!("cannot read input NPY {path}"))?;

    if x.ncols() != nx {
        bail!(
            "invalid input dimension in NPY {}: expected {} columns, got {}",
            path,
            nx,
            x.ncols()
        );
    }

    if x.nrows() == 0 {
        bail!("input NPY {path} does not contain any sample row");
    }

    Ok(x)
}

fn read_input_data(path: &str, nx: usize, format: DataFormat) -> Result<Array2<f64>> {
    match format {
        DataFormat::Csv => read_input_csv(path, nx),
        DataFormat::Npy => read_input_npy(path, nx),
    }
}

fn read_training_csv(path: &str) -> Result<(Array2<f64>, Array1<f64>)> {
    let content =
        fs::read_to_string(path).with_context(|| format!("cannot read training CSV {path}"))?;

    let mut nrows = 0usize;
    let mut nx = 0usize;
    let mut x_flat_values = Vec::new();
    let mut y_values = Vec::new();
    let mut first_non_empty = true;

    for (line_index, raw_line) in content.lines().enumerate() {
        let line = raw_line.trim();
        if line.is_empty() {
            continue;
        }

        let row = match parse_csv_row(line) {
            Ok(row) => row,
            Err(_e) if first_non_empty && is_header_row(line) => {
                first_non_empty = false;
                continue;
            }
            Err(e) => {
                return Err(e).with_context(|| {
                    format!("invalid training CSV row at line {}", line_index + 1)
                });
            }
        };
        first_non_empty = false;

        if row.len() < 2 {
            bail!(
                "invalid training row at line {}: expected at least 2 columns (features + output), got {}",
                line_index + 1,
                row.len()
            );
        }

        if nx == 0 {
            nx = row.len() - 1;
        } else if row.len() != nx + 1 {
            bail!(
                "inconsistent training row width at line {}: expected {} columns, got {}",
                line_index + 1,
                nx + 1,
                row.len()
            );
        }

        x_flat_values.extend_from_slice(&row[..nx]);
        y_values.push(row[nx]);
        nrows += 1;
    }

    if nrows == 0 {
        bail!("training CSV {path} does not contain any sample row");
    }

    let x = Array2::from_shape_vec((nrows, nx), x_flat_values)
        .map_err(|e| anyhow!("cannot build training input matrix from CSV {path}: {e}"))?;
    let y = Array1::from_vec(y_values);
    Ok((x, y))
}

fn read_training_npy(path: &str) -> Result<(Array2<f64>, Array1<f64>)> {
    let xy: Array2<f64> =
        read_npy(path).with_context(|| format!("cannot read training NPY {path}"))?;

    if xy.ncols() < 2 {
        bail!(
            "invalid training NPY {}: expected at least 2 columns (features + output), got {}",
            path,
            xy.ncols()
        );
    }

    if xy.nrows() == 0 {
        bail!("training NPY {path} does not contain any sample row");
    }

    let nx = xy.ncols() - 1;
    let x = xy.slice(ndarray::s![.., ..nx]).to_owned();
    let y = xy.column(nx).to_owned();
    Ok((x, y))
}

fn read_training_data(path: &str, format: DataFormat) -> Result<(Array2<f64>, Array1<f64>)> {
    match format {
        DataFormat::Csv => read_training_csv(path),
        DataFormat::Npy => read_training_npy(path),
    }
}

fn write_predictions_csv(
    path: &str,
    values: &Array1<f64>,
    variances: Option<&Array1<f64>>,
) -> Result<()> {
    if let Some(var) = variances
        && var.len() != values.len()
    {
        bail!(
            "variance vector length mismatch: expected {}, got {}",
            values.len(),
            var.len()
        );
    }

    let mut out = String::new();
    if variances.is_some() {
        out.push_str("prediction,variance\n");
    } else {
        out.push_str("prediction\n");
    }

    for i in 0..values.len() {
        if let Some(var) = variances {
            out.push_str(&format!("{:.16e},{:.16e}\n", values[i], var[i]));
        } else {
            out.push_str(&format!("{:.16e}\n", values[i]));
        }
    }

    fs::write(path, out).with_context(|| format!("cannot write output CSV {path}"))
}

fn write_predictions_npy(
    path: &str,
    values: &Array1<f64>,
    variances: Option<&Array1<f64>>,
) -> Result<()> {
    if let Some(var) = variances
        && var.len() != values.len()
    {
        bail!(
            "variance vector length mismatch: expected {}, got {}",
            values.len(),
            var.len()
        );
    }

    let nrows = values.len();
    let ncols = if variances.is_some() { 2 } else { 1 };
    let mut flat = Vec::with_capacity(nrows * ncols);

    for i in 0..nrows {
        flat.push(values[i]);
        if let Some(var) = variances {
            flat.push(var[i]);
        }
    }

    let out = Array2::from_shape_vec((nrows, ncols), flat)
        .map_err(|e| anyhow!("cannot build prediction output matrix: {e}"))?;
    write_npy(path, &out).with_context(|| format!("cannot write output NPY {path}"))
}

fn write_predictions_data(
    path: &str,
    format: DataFormat,
    values: &Array1<f64>,
    variances: Option<&Array1<f64>>,
) -> Result<()> {
    match format {
        DataFormat::Csv => write_predictions_csv(path, values, variances),
        DataFormat::Npy => write_predictions_npy(path, values, variances),
    }
}

fn run_qa(model: &str, kfold: usize) -> Result<()> {
    let gp_models = load_models(model)?;

    println!("Loaded {} GP model(s) from {}", gp_models.len(), model);
    gp_models.iter().for_each(|gp| {
        println!("Loaded GP model: {}", gp);
    });

    let (xt, _yt) = gp_models.first().unwrap().training_data();
    println!("Training data: {} samples ({}-dim)", xt.nrows(), xt.ncols());

    let k = if kfold == 0 { xt.nrows() } else { kfold };
    let res: Vec<_> = compute_metrics(&gp_models, k);

    for (i, m) in res.iter().enumerate() {
        println!(
            "GP({}): Q2 = {:.2}, PVA = {:.2}, IAEα = {:.2}",
            i, m.q2, m.pva, m.iae_alpha
        );
    }

    Ok(())
}

fn run_fit(input: &str, input_format: DataFormat, output: &str, format: ModelFormat) -> Result<()> {
    let (x, y) = read_training_data(input, input_format)?;
    let ds = Dataset::new(x, y);

    let gp = GpMixture::params()
        .fit(&ds)
        .map_err(|e| anyhow!("default GP training failed: {e}"))?;

    match format {
        ModelFormat::Binary => {
            let bytes = bincode::serde::encode_to_vec(&gp, bincode::config::standard())
                .map_err(|e| anyhow!("cannot serialize trained model to binary: {e}"))?;
            fs::write(output, bytes)
                .with_context(|| format!("cannot write binary model file {output}"))?;
        }
        ModelFormat::Json => {
            let text =
                serde_json::to_string_pretty(&gp).map_err(|e| anyhow!("cannot serialize trained model to JSON: {e}"))?;
            fs::write(output, text)
                .with_context(|| format!("cannot write JSON model file {output}"))?;
        }
    }

    let (nx, ny) = gp.dims();
    println!("Trained default GP surrogate from {input}");
    println!("Training samples: {}", ds.records().nrows());
    println!("Input dimension: {nx}");
    println!("Output dimension: {ny}");
    println!("Input format: {:?}", input_format);
    println!("Output format: {:?}", format);
    println!("Saved model to {output}");

    Ok(())
}

fn run_spec(model: &str, model_index: usize) -> Result<()> {
    let gp_models = load_models(model)?;
    let gp = select_model(&gp_models, model_index)?;
    let (xt, _yt) = gp.training_data();
    let (nx, ny) = gp.dims();

    println!("Executable: gpx");
    println!("Subcommand: spec");
    println!("Model file: {model}");
    println!("Model count in file: {}", gp_models.len());
    println!("Selected model index: {model_index}");
    println!("Selected model summary: {gp}");
    println!("Input specification:");
    println!("  - supported formats: csv, npy");
    println!("  - csv row layout: x1,x2,...,x{nx}");
    println!("  - npy array shape: (n_samples, {nx})");
    println!("  - expected input dimension: {nx}");
    println!("Output specification:");
    println!("  - primary output dimension: {ny}");
    println!("  - predict csv columns: prediction");
    println!("  - predict --with-variance csv columns: prediction,variance");
    println!("  - predict npy shape: (n_samples, 1)");
    println!("  - predict --with-variance npy shape: (n_samples, 2)");
    println!("Training data summary:");
    println!("  - samples: {}", xt.nrows());
    println!("  - input dimension: {}", xt.ncols());

    Ok(())
}

fn run_predict(
    model: &str,
    input: &str,
    input_format: DataFormat,
    output: &str,
    output_format: DataFormat,
    with_variance: bool,
    model_index: usize,
) -> Result<()> {
    let gp_models = load_models(model)?;
    let gp = select_model(&gp_models, model_index)?;
    let (nx, _ny) = gp.dims();

    let x = read_input_data(input, nx, input_format)?;
    let pred = gp.predict(&x.view())?;

    let variances = if with_variance {
        Some(gp.predict_var(&x.view())?)
    } else {
        None
    };

    write_predictions_data(output, output_format, &pred, variances.as_ref())?;

    println!(
        "Predicted {} sample(s) from {} and wrote {}",
        x.nrows(),
        input,
        output
    );
    println!("Model file: {model} (index {model_index})");
    println!("Input format: {:?}", input_format);
    println!("Output format: {:?}", output_format);
    match output_format {
        DataFormat::Csv => {
            if with_variance {
                println!("Output columns: prediction,variance");
            } else {
                println!("Output columns: prediction");
            }
        }
        DataFormat::Npy => {
            if with_variance {
                println!("Output array shape: (n_samples, 2) [prediction, variance]");
            } else {
                println!("Output array shape: (n_samples, 1) [prediction]");
            }
        }
    }

    Ok(())
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Fit {
            input,
            input_format,
            output,
            format,
        } => run_fit(&input, input_format, &output, format),
        Commands::Qa { model, kfold } => run_qa(&model, kfold),
        Commands::Spec { model, model_index } => run_spec(&model, model_index),
        Commands::Predict {
            model,
            input,
            input_format,
            output,
            output_format,
            with_variance,
            model_index,
        } => run_predict(
            &model,
            &input,
            input_format,
            &output,
            output_format,
            with_variance,
            model_index,
        ),
    }
}
