//! Command-line entrypoint for the `gpx` executable.
//!
//! This module defines the CLI surface and dispatches each subcommand
//! to its implementation module.

mod commands;
mod io;
mod services;

use anyhow::Result;
use clap::{Parser, Subcommand, ValueEnum};
use egobox_moe::{CorrelationSpec, RegressionSpec};

use crate::commands::{run_fit, run_predict, run_qa, run_spec};

#[derive(Parser)]
#[command(author, version, about, long_about = None)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Commands,
}

#[derive(Copy, Clone, Debug, ValueEnum)]
pub enum ModelFormat {
    Json,
    Binary,
}

#[derive(Copy, Clone, Debug, ValueEnum)]
pub enum DataFormat {
    Csv,
    Npy,
}

#[derive(Copy, Clone, Debug, ValueEnum)]
pub enum RegressionChoice {
    Constant,
    Linear,
    Quadratic,
    All,
}

impl From<RegressionChoice> for RegressionSpec {
    fn from(value: RegressionChoice) -> Self {
        match value {
            RegressionChoice::Constant => RegressionSpec::CONSTANT,
            RegressionChoice::Linear => RegressionSpec::LINEAR,
            RegressionChoice::Quadratic => RegressionSpec::QUADRATIC,
            RegressionChoice::All => RegressionSpec::ALL,
        }
    }
}

#[derive(Copy, Clone, Debug, ValueEnum)]
pub enum CorrelationChoice {
    SquaredExponential,
    AbsoluteExponential,
    Matern32,
    Matern52,
    All,
}

impl From<CorrelationChoice> for CorrelationSpec {
    fn from(value: CorrelationChoice) -> Self {
        match value {
            CorrelationChoice::SquaredExponential => CorrelationSpec::SQUAREDEXPONENTIAL,
            CorrelationChoice::AbsoluteExponential => CorrelationSpec::ABSOLUTEEXPONENTIAL,
            CorrelationChoice::Matern32 => CorrelationSpec::MATERN32,
            CorrelationChoice::Matern52 => CorrelationSpec::MATERN52,
            CorrelationChoice::All => CorrelationSpec::ALL,
        }
    }
}

#[derive(Copy, Clone, Debug, ValueEnum)]
pub enum RecombinationChoice {
    Hard,
    Smooth,
}

#[derive(Subcommand)]
pub enum Commands {
    /// Fit GP surrogates from tabular data
    Fit {
        /// Training input file
        input: String,

        /// Number of output columns taken from the end of each training row
        #[arg(long, default_value_t = 1)]
        outputs: usize,

        /// Regression model specification used when fitting each surrogate
        #[arg(long, value_enum, default_value_t = RegressionChoice::Constant)]
        regression_spec: RegressionChoice,

        /// Correlation model specification used when fitting each surrogate
        #[arg(long, value_enum, default_value_t = CorrelationChoice::SquaredExponential)]
        correlation_spec: CorrelationChoice,

        /// Optional number of PLS components for KPLS dimension reduction
        #[arg(long)]
        kpls_dim: Option<usize>,

        /// Number of clusters (number of local experts)
        #[arg(long, default_value_t = 1)]
        n_clusters: usize,

        /// Recombination mode used to combine experts
        #[arg(long, value_enum, default_value_t = RecombinationChoice::Smooth)]
        recombination: RecombinationChoice,

        /// Optional smooth recombination factor (used only when recombination is smooth)
        #[arg(long)]
        smooth_factor: Option<f64>,

        /// Output model file path
        #[arg(short, long, default_value = "surrogate_model.gpx")]
        output: String,
    },
    /// Assess quality metrics of one or several GP models
    Qa {
        /// GP file generated by Egor optimizer or Gpx save
        #[arg(long, default_value = "surrogate_model.gpx")]
        model: String,

        /// Optional model index to assess a single surrogate; if omitted, all models are used
        #[arg(short = 'm', long)]
        model_index: Option<usize>,

        /// Use K folding cross validation procedure (default LOO)
        #[arg(short, long, default_value_t = 0)]
        kfold: usize,
    },
    /// Display GP model input/output specifications
    Spec {
        /// GP file generated by Egor optimizer or Gpx save
        #[arg(long, default_value = "surrogate_model.gpx")]
        model: String,

        /// Optional model index to inspect a single surrogate; if omitted, all models are shown
        #[arg(short = 'm', long)]
        model_index: Option<usize>,
    },
    /// Predict outputs for tabular input samples
    Predict {
        /// Input file containing one sample per row
        input: String,

        /// GP file generated by Egor optimizer or Gpx save
        #[arg(long, default_value = "surrogate_model.gpx")]
        model: String,

        /// Output file where predictions are written
        #[arg(short, long, default_value = "surrogate_predictions.csv")]
        output: String,

        /// Include predictive variance in output data
        #[arg(long, default_value_t = false)]
        with_variance: bool,

        /// Optional model index to predict a single output; if omitted, all models are used
        #[arg(short = 'm', long)]
        model_index: Option<usize>,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Fit {
            input,
            outputs,
            regression_spec,
            correlation_spec,
            kpls_dim,
            n_clusters,
            recombination,
            smooth_factor,
            output,
        } => run_fit(
            &input,
            outputs,
            regression_spec,
            correlation_spec,
            kpls_dim,
            n_clusters,
            recombination,
            smooth_factor,
            &output,
        ),
        Commands::Qa {
            model,
            model_index,
            kfold,
        } => run_qa(&model, model_index, kfold),
        Commands::Spec { model, model_index } => run_spec(&model, model_index),
        Commands::Predict {
            input,
            model,
            output,
            with_variance,
            model_index,
        } => run_predict(&model, &input, &output, with_variance, model_index),
    }
}
