use anyhow::Result;
use clap::Parser;
#[allow(unused_imports)]
// Though not directly used, this import is required for bincode
// to properly load MixintGpMixture (while serde_json does not need it)
use egobox_ego::gpmix::mixint::MixintGpMixture;
use egobox_moe::MixtureGpSurrogate;
use rayon::prelude::*;
use std::fs;

#[derive(Parser)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// Binary GP file generated by Egor optimizer
    filename: String,

    /// Use leave one out cross validation procedure
    #[arg(short, long, default_value_t = false)]
    loo: bool,

    /// Use K folding cross validation procedure
    #[arg(short, long, default_value = "5")]
    kfold: usize,
}

fn main() -> Result<()> {
    let args = Args::parse();

    let data: Vec<u8> = fs::read(&args.filename)?;
    let gp_models: Vec<Box<dyn MixtureGpSurrogate>> =
        bincode::serde::decode_from_slice(&data[..], bincode::config::standard())
            .map(|(res, _)| res)?;

    let _res: Vec<_> = gp_models
        .par_iter()
        .enumerate()
        .map(|(i, gp)| {
            let q2 = if args.loo {
                gp.as_ref().looq2()
            } else {
                gp.as_ref().q2(args.kfold)
            };

            let pva = if args.loo {
                gp.as_ref().loopva()
            } else {
                gp.as_ref().pva(args.kfold)
            };
            let n = gp.training_data().0.nrows();
            println!("GP({i}): nbpts={n}, Q2={q2}, PVA={pva}");
        })
        .collect();

    Ok(())
}
