# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import numpy
import numpy.typing
import typing
__all__ = [
    "ConstraintStrategy",
    "CorrelationSpec",
    "CstrSpec",
    "Egor",
    "EgorOptim",
    "ExitStatus",
    "FailsafeStrategy",
    "FeasibleInfillStrategy",
    "GpConfig",
    "GpMix",
    "Gpx",
    "InfillOptimizer",
    "InfillStrategy",
    "OptimResult",
    "QEiConfig",
    "QEiStrategy",
    "Recombination",
    "RegressionSpec",
    "RunInfo",
    "RunStatus",
    "Sampling",
    "SparseGpMix",
    "SparseGpx",
    "SparseMethod",
    "TregoConfig",
    "Verbose",
    "XSpec",
    "XType",
    "lhs",
    "sampling",
]

@typing.final
class CorrelationSpec:
    r"""
    CorrelationSpec is a bitfield that specifies which correlation terms to include in the model.
    """
    ALL: builtins.int = 15
    SQUARED_EXPONENTIAL: builtins.int = 1
    ABSOLUTE_EXPONENTIAL: builtins.int = 2
    MATERN32: builtins.int = 4
    MATERN52: builtins.int = 8

@typing.final
class CstrSpec:
    r"""
    CstrSpec specifies how a constraint should be interpreted by the optimizer.
    
    Instead of requiring constraints to be formulated as c <= 0,
    users can specify constraint bounds directly.
    
    # Examples
    
    ```python
    import egobox as egx
    
    # c <= 5.0
    spec1 = egx.CstrSpec.leq(5.0)
    
    # c >= 2.0
    spec2 = egx.CstrSpec.geq(2.0)
    
    # c = 4.0 (equality constraint, expands to two internal constraints)
    spec3 = egx.CstrSpec.eq(4.0)
    
    # 1.0 <= c <= 3.0 (double-sided, expands to two internal constraints)
    spec4 = egx.CstrSpec.btw(1.0, 3.0)
    ```
    """
    @staticmethod
    def leq(bound: builtins.float) -> CstrSpec:
        r"""
        Constraint c <= bound, transformed to c - bound <= 0
        """
    @staticmethod
    def geq(bound: builtins.float) -> CstrSpec:
        r"""
        Constraint c >= bound, transformed to bound - c <= 0
        """
    @staticmethod
    def eq(value: builtins.float) -> CstrSpec:
        r"""
        Equality constraint c = value, expands to two internal constraints:
        c - value <= 0 and value - c <= 0
        """
    @staticmethod
    def btw(lower: builtins.float, upper: builtins.float) -> CstrSpec:
        r"""
        Double-sided constraint lower <= c <= upper, expands to two internal constraints:
        lower - c <= 0 and c - upper <= 0
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Egor:
    r"""
    Optimizer constructor
    
    Parameters
    ----------
    xspecs : list of XSpec, list of [lower, upper] or array[nx, 2]
        Specifications of the nx components of the input x (eg. len(xspecs) == nx),
        with XSpec(xtype=FLOAT|INT|ORD|ENUM, xlimits=[<f(xtype)>] or tags=[strings]).
        Depending on the x type we get the following for xlimits:
    
        * when FLOAT: xlimits is [float lower_bound, float upper_bound],
        * when INT: xlimits is [int lower_bound, int upper_bound],
        * when ORD: xlimits is [float_1, float_2, ..., float_n],
        * when ENUM: xlimits is just the int size of the enumeration otherwise a list of tags is specified
          (eg xlimits=[3] or tags=["red", "green", "blue"], tags are there for documentation purpose but
          tags specific values themselves are not used only indices in the enum are used hence
          we can just specify the size of the enum, xlimits=[3]).
    gp_config : GpConfig or dict, optional
        GP configuration used by the optimizer, see GpConfig for details.
    n_cstr : int
        Number of constraints returned by `fun` (see `minimize`) which will be approximated by surrogates.
        Can be omitted when `cstr_specs` is given.
    cstr_tol : list of float, optional
        Tolerances for constraints to be satisfied (cstr < tol).
        The list must cover all internal constraints: the `n_cstr` surrogate constraints
        (after `cstr_specs` expansion, see below) followed by the function constraints
        `fcstrs` given to `minimize` (after `fcstr_specs` expansion).
        When None, tolerances default to DEFAULT_CSTR_TOL=1e-4.
    cstr_specs : list of CstrSpec or dict, optional
        Describe how each surrogate-modeled constraint (returned by `fun`) should be interpreted.
        This allows users to define bounds directly instead of manually rewriting
        constraints in `c <= 0` form:
    
        * CstrSpec.leq(bound): c <= bound (less or equal)
        * CstrSpec.geq(bound): c >= bound (greater or equal)
        * CstrSpec.eq(value): c == value (expands to two internal constraints)
        * CstrSpec.btw(lower, upper): lower <= c <= upper (between, expands to two internal constraints)
    
        When set, `n_cstr` is inferred from `len(cstr_specs)` (`n_cstr` is ignored if set to zero,
        or must match otherwise).
    n_start : int > 0
        Number of starts of the multistart optimization of the infill criterion (best result taken).
        Not to be confused with `GpConfig(n_start=...)`, the GP hyperparameters optimization multistart.
    n_doe : int >= 0
        Number of samples of initial LHS sampling (used when DOE not provided by the user).
        When 0 a number of points is computed automatically regarding the number of input variables
        of the function under optimization.
    doe : array[ns, nt], optional
        Initial DOE containing ns samples:
        either nt = nx then only x are specified and ns evals are done to get y doe values,
        or nt = nx + ny then x = doe[:, :nx] and y = doe[:, nx:] are specified.
        Note that `suggest` takes x and y as two separate arrays `x_doe` and `y_doe`.
    infill_strategy : InfillStrategy
        Infill criterion to decide best next promising point.
        Can be either InfillStrategy.LOG_EI (default), InfillStrategy.EI, InfillStrategy.WB2, InfillStrategy.WB2S
    feasible_infill_strategy : FeasibleInfillStrategy
        Weight the infill criterion by the probability of viability to avoid regions where
        `fun` fails (hidden constraints). Can be either FeasibleInfillStrategy.NONE (default),
        FeasibleInfillStrategy.EFI_P, or FeasibleInfillStrategy.EFI_FE.
        Independent of `cstr_infill`, both can be used together.
    cstr_infill : bool
        Activate constrained infill criterion where the product of probabilities of feasibility
        of the `n_cstr` surrogate constraints is used as a factor of the infill criterion.
        Independent of `feasible_infill_strategy`, both can be used together.
    cstr_strategy : ConstraintStrategy
        Constraint management, either use the mean value or the upper trust bound of the constraint surrogates.
        Can be either ConstraintStrategy.MC (mean constraint, default) or ConstraintStrategy.UTB (upper trust bound).
    qei_config : QEiConfig or dict, optional
        Configuration for parallel (qEI) evaluation also known as batch or multipoint evaluation.
        q points are selected at each iteration of the EGO algorithm.
        See QEiConfig for details.
    infill_optimizer : InfillOptimizer
        Internal optimizer used to optimize infill criteria.
        Can be either InfillOptimizer.COBYLA (default) or InfillOptimizer.SLSQP
    trego : TregoConfig, bool or dict, optional
        TREGO configuration to activate TREGO strategy for global optimization.
        When True activate TREGO with default configuration.
        To activate TREGO with custom configuration see TregoConfig for details.
        When None or False TREGO is not used.
    coego_n_coop : int >= 0
        Number of cooperative components groups which will be used by the CoEGO algorithm.
        Better to have n_coop a divider of nx or if not with a remainder as large as possible.
        The CoEGO algorithm is used to tackle high-dimensional problems turning it in a set of
        partial optimizations using only nx / n_coop components at a time.
        The default value is 0 meaning that the CoEGO algorithm is not used.
    target : float, optional
        Known optimum used as stopping criterion: the optimization stops once
        an objective value lower than or equal to target is found.
        When None (default) no target is used.
    failsafe_strategy : FailsafeStrategy
        Strategy to handle objective computation failure at a given x point.
        A failure is detected when the objective function returns NaN value(s).
        Can be either FailsafeStrategy.REJECTION (default), FailsafeStrategy.IMPUTATION, or FailsafeStrategy.VIABILITY.
        Rejection simply ignores the failed point whereas Imputation
        uses the objective surrogate prediction to fill the missing value.
        In the third case Viability, a surrogate is used to model the failure region
        which is used as a constraint and drive the optimization toward the viable region.
    
    Returns
    -------
    Egor
        An optimizer which can be used to optimize a function using the minimize method.
        Random seed and logging verbosity are given to `minimize()`, not to the constructor.
    """
    def __new__(cls, xspecs: typing.Sequence[XSpec] | typing.Sequence[typing.Sequence[builtins.float]] | numpy.typing.NDArray[numpy.float64], gp_config: GpConfig | builtins.dict[builtins.str, typing.Any] | None = None, n_cstr: builtins.int = 0, cstr_tol: typing.Optional[typing.Sequence[builtins.float]] = None, cstr_specs: typing.Sequence[CstrSpec | builtins.dict[builtins.str, typing.Any]] | None = None, n_start: builtins.int = 20, n_doe: builtins.int = 0, doe: typing.Optional[numpy.typing.NDArray[numpy.float64]] = None, infill_strategy: InfillStrategy = InfillStrategy.LOG_EI, feasible_infill_strategy: FeasibleInfillStrategy = FeasibleInfillStrategy.NONE, cstr_infill: builtins.bool = False, cstr_strategy: ConstraintStrategy = ConstraintStrategy.MC, qei_config: QEiConfig | builtins.dict[builtins.str, typing.Any] | None = None, infill_optimizer: InfillOptimizer = InfillOptimizer.COBYLA, trego: TregoConfig | builtins.bool | builtins.dict[builtins.str, typing.Any] | None = None, coego_n_coop: builtins.int = 0, target: typing.Optional[builtins.float] = None, failsafe_strategy: FailsafeStrategy = FailsafeStrategy.REJECTION) -> Egor: ...
    def minimize(self, fun: typing.Callable[[numpy.typing.NDArray[numpy.float64]], numpy.typing.NDArray[numpy.float64]], fcstrs: typing.Sequence[typing.Callable[[numpy.typing.NDArray[numpy.float64], builtins.bool], builtins.float | numpy.typing.NDArray[numpy.float64]]] | None = None, fcstr_specs: typing.Sequence[CstrSpec | builtins.dict[builtins.str, typing.Any]] | None = None, max_iters: builtins.int = 20, run_info: RunInfo | builtins.dict[builtins.str, typing.Any] | None = None, outdir: typing.Optional[builtins.str] = None, warm_start: builtins.bool = False, hot_start: builtins.bool | builtins.int | None = None, seed: typing.Optional[builtins.int] = None, timeout: typing.Optional[builtins.float] = None, verbose: Verbose | builtins.int | None = None, stop_on_error: builtins.bool = False) -> EgorOptim:
        r"""
        This function finds the minimum of a given function "fun"
        
        Parameters
        ----------
        fun : callable (array[n, nx]) -> array[n, ny]
            The function to be minimized: fun(x) = [obj(x), cstr_1(x), ... cstr_k(x)] where
        
            * obj is the objective function [n, nx] -> [n, 1]
            * cstr_i is the ith constraint function [n, nx] -> [n, 1]
            * k is the number of constraints (n_cstr), hence ny = 1 (obj) + k (cstrs)
        
            cstr functions are expected to be negative (<=0) at the optimum (unless `cstr_specs` is used).
            These constraints will be approximated using surrogates, so
            if constraints are cheap to evaluate better to pass them through `fcstrs`.
        fcstrs : list of callable (array[nx], bool) -> float or array[nx], optional
            Constraint functions defined as g(x, return_grad).
            If the given "return_grad" boolean is False the function has to return the constraint float value
            to be made negative by the optimizer (which drives the input array "x").
            Otherwise the function has to return the gradient (array[nx]) of the constraint function
            wrt the nx components of "x".
        fcstr_specs : list of CstrSpec or dict, optional
            One CstrSpec per fcstr specifying how each function constraint should be interpreted.
            Length must be zero (legacy behavior) or equal to len(fcstrs).
            This allows raw constraints not written as c <= 0, for example:
            CstrSpec.leq(b), CstrSpec.geq(b), CstrSpec.eq(v), CstrSpec.btw(lo, hi).
            Note: CstrSpec.eq and CstrSpec.btw expand to two internal constraints each.
            When `cstr_tol` is explicitly provided, ensure its size covers all internal
            constraints: surrogate constraints + expanded function constraints.
        max_iters : int
            The iteration budget, number of fun calls is "n_doe + q_batch * max_iters".
            Not to be confused with `GpConfig(max_eval=...)`, the likelihood evaluations budget.
        run_info : RunInfo or dict, optional
            Information about the run to be passed to the optimizer with the following attributes:
        
            * fname (str): name of the function under optimization, used for checkpoint file naming
            * num (int): number of the run, used for checkpoint file naming
        outdir : str, optional
            Directory to write optimization history and used as search path for warm start doe
        warm_start : bool
            Start by loading initial doe from <outdir> directory
        hot_start : bool or int >= 0, optional
            When hot_start>=0 saves optimizer state at each iteration and starts from a previous checkpoint
            for the given hot_start number of iterations beyond the max_iters nb of iterations.
            In an unstable environment where there can be crashes it allows to restart the optimization
            from the last iteration till stopping criterion is reached. Just use hot_start=0 in this case.
            When True, hot_start behaves like hot_start=0 with no iteration extension.
            Checkpoint information is stored in .checkpoint or under outdir if outdir is specified.
        seed : int >= 0, optional
            Random generator seed to allow computation reproducibility.
            Unlike `GpMix` where seed is given at construction, it is given here at each run.
        timeout : float, optional
            Timeout in seconds. The optimization is stopped when the elapsed time
            exceeds this duration. The actual runtime may slightly exceed the specified timeout
            as the check is performed after each iteration.
        verbose : Verbose or int, optional
            Logging verbosity level for the optimizer.
            Can be either an integer or a Verbose enum value:
            0 or Verbose.ERROR, 1 or Verbose.WARNING, 2 or Verbose.INFO,
            3 or Verbose.DEBUG, 4 (or greater) or Verbose.TRACE.
            Default is None which means Verbose.ERROR level and possible control by
            the EGOBOX_LOG environment variable.
            Unlike `GpMix` where verbose is given at construction, it is given here at each run.
        stop_on_error : bool
            If true, terminate optimization when the objective function raises an error.
            Otherwise, the error is handled according to failsafe_strategy.
        
        Returns
        -------
        EgorOptim
            result (OptimResult) and status (RunStatus) of the optimization, where result holds:
        
            * x_opt (array[nx]): x value where fun is at its minimum subject to constraints
            * y_opt (array[ny]): fun(x_opt) where ny = 1 + n_cstr
            * x_doe (array[ns, nx]): x values of the final DOE
            * y_doe (array[ns, ny]): y values of the final DOE
        """
    def suggest(self, x_doe: numpy.typing.NDArray[numpy.float64], y_doe: numpy.typing.NDArray[numpy.float64], seed: typing.Optional[builtins.int] = None) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        This function gives the next best location where to evaluate the function
        under optimization wrt to previous evaluations.
        The function returns several points when multi point qEI strategy is used.
        
        Parameters
        ----------
        x_doe : array[ns, nx]
            ns samples where function has been evaluated
        y_doe : array[ns, 1 + n_cstr]
            ns values of objective and constraints
        seed : int >= 0, optional
            Random generator seed to allow computation reproducibility.
        
        Returns
        -------
        array[batch, nx]
            suggested locations where to evaluate objective and constraints
            where batch is the qEI batch size (qei_config.batch, 1 by default)
        """
    def get_result_index(self, y_doe: numpy.typing.NDArray[numpy.float64]) -> builtins.int:
        r"""
        This function gives the best evaluation index given the outputs
        of the function (objective wrt constraints) under minimization.
        Caveat: This function does not take into account function constraints values
        
        Parameters
        ----------
        y_doe : array[ns, 1 + n_cstr]
            ns values of objective and constraints
        
        Returns
        -------
        int
            index in y_doe of the best evaluation
        """
    def get_result(self, x_doe: numpy.typing.NDArray[numpy.float64], y_doe: numpy.typing.NDArray[numpy.float64]) -> OptimResult:
        r"""
        This function gives the best result given inputs and outputs
        of the function (objective wrt constraints) under minimization.
        Caveat: This function does not take into account function constraints values
        
        Parameters
        ----------
        x_doe : array[ns, nx]
            ns samples where function has been evaluated
        y_doe : array[ns, 1 + n_cstr]
            ns values of objective and constraints
        
        Returns
        -------
        OptimResult
            * x_opt (array[nx]): x value where fun is at its minimum subject to constraints
            * y_opt (array[ny]): fun(x_opt) where ny = 1 + n_cstr
            * x_doe (array[ns, nx]): the given x_doe
            * y_doe (array[ns, ny]): the given y_doe
        """

@typing.final
class EgorOptim:
    r"""
    Egor optimization output
    """
    @property
    def result(self) -> OptimResult:
        r"""
        Result of optimization run
        """
    @property
    def status(self) -> RunStatus:
        r"""
        Status of optimization run
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class GpConfig:
    r"""
    GP configuration used by `Egor` and `GpMix`
    """
    @property
    def regr_spec(self) -> builtins.int:
        r"""
        (RegressionSpec flags, an int in [1, 7])
        Specification of regression models used in mixture.
        Can be RegressionSpec.CONSTANT (1), RegressionSpec.LINEAR (2), RegressionSpec.QUADRATIC (4) or
        any bit-wise union of these values (e.g. RegressionSpec.CONSTANT | RegressionSpec.LINEAR)
        """
    @regr_spec.setter
    def regr_spec(self, value: builtins.int) -> None:
        r"""
        (RegressionSpec flags, an int in [1, 7])
        Specification of regression models used in mixture.
        Can be RegressionSpec.CONSTANT (1), RegressionSpec.LINEAR (2), RegressionSpec.QUADRATIC (4) or
        any bit-wise union of these values (e.g. RegressionSpec.CONSTANT | RegressionSpec.LINEAR)
        """
    @property
    def corr_spec(self) -> builtins.int:
        r"""
        (CorrelationSpec flags, an int in [1, 15])
        Specification of correlation models used in mixture.
        Can be CorrelationSpec.SQUARED_EXPONENTIAL (1), CorrelationSpec.ABSOLUTE_EXPONENTIAL (2),
        CorrelationSpec.MATERN32 (4), CorrelationSpec.MATERN52 (8) or
        any bit-wise union of these values (e.g. CorrelationSpec.MATERN32 | CorrelationSpec.MATERN52)
        """
    @corr_spec.setter
    def corr_spec(self, value: builtins.int) -> None:
        r"""
        (CorrelationSpec flags, an int in [1, 15])
        Specification of correlation models used in mixture.
        Can be CorrelationSpec.SQUARED_EXPONENTIAL (1), CorrelationSpec.ABSOLUTE_EXPONENTIAL (2),
        CorrelationSpec.MATERN32 (4), CorrelationSpec.MATERN52 (8) or
        any bit-wise union of these values (e.g. CorrelationSpec.MATERN32 | CorrelationSpec.MATERN52)
        """
    @property
    def kpls_dim(self) -> typing.Optional[builtins.int]:
        r"""
        (0 < int < nx where nx is the dimension of inputs x)
        Number of components to be used when PLS projection is used (a.k.a KPLS method).
        This is used to address high-dimensional problems typically when nx > 9.
        """
    @kpls_dim.setter
    def kpls_dim(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        (0 < int < nx where nx is the dimension of inputs x)
        Number of components to be used when PLS projection is used (a.k.a KPLS method).
        This is used to address high-dimensional problems typically when nx > 9.
        """
    @property
    def n_clusters(self) -> builtins.int:
        r"""
        (int)
        Number of clusters used by the mixture of surrogate experts (default is 1).
        When set to 0, the number of cluster is determined automatically and refreshed every
        10-points addition (should say 'tentative addition' because addition may fail for some points
        but it is counted anyway).
        When set to negative number -n, the number of clusters is determined automatically in [1, n]
        this is used to limit the number of trials hence the execution time.
        """
    @n_clusters.setter
    def n_clusters(self, value: builtins.int) -> None:
        r"""
        (int)
        Number of clusters used by the mixture of surrogate experts (default is 1).
        When set to 0, the number of cluster is determined automatically and refreshed every
        10-points addition (should say 'tentative addition' because addition may fail for some points
        but it is counted anyway).
        When set to negative number -n, the number of clusters is determined automatically in [1, n]
        this is used to limit the number of trials hence the execution time.
        """
    @property
    def recombination(self) -> Recombination:
        r"""
        (Recombination.SMOOTH or Recombination.HARD (default))
        Specify how the various experts predictions are recombined
        * SMOOTH: prediction is a combination of experts prediction wrt their responsibilities,
        the heaviside factor which controls steepness of the change between experts regions is optimized
        to get best mixture quality.
        * HARD: prediction is taken from the expert with highest responsibility
        resulting in a model with discontinuities.
        """
    @recombination.setter
    def recombination(self, value: Recombination) -> None:
        r"""
        (Recombination.SMOOTH or Recombination.HARD (default))
        Specify how the various experts predictions are recombined
        * SMOOTH: prediction is a combination of experts prediction wrt their responsibilities,
        the heaviside factor which controls steepness of the change between experts regions is optimized
        to get best mixture quality.
        * HARD: prediction is taken from the expert with highest responsibility
        resulting in a model with discontinuities.
        """
    @property
    def theta_init(self) -> typing.Optional[builtins.list[builtins.float]]:
        r"""
        ([nx] where nx is the dimension of inputs x)
        Initial guess for GP theta hyperparameters.
        When None the default is 1e-1 for all components
        """
    @theta_init.setter
    def theta_init(self, value: typing.Optional[typing.Sequence[builtins.float]]) -> None:
        r"""
        ([nx] where nx is the dimension of inputs x)
        Initial guess for GP theta hyperparameters.
        When None the default is 1e-1 for all components
        """
    @property
    def theta_bounds(self) -> typing.Optional[builtins.list[builtins.list[builtins.float]]]:
        r"""
        ([[lower_1, upper_1], ..., [lower_nx, upper_nx]] where nx is the dimension of inputs x)
        Space search when optimizing theta GP hyperparameters
        When None the default is [1e-2, 1e1] for all components.
        Note: `Egor` may adapt these bounds automatically for high-dimensional inputs.
        """
    @theta_bounds.setter
    def theta_bounds(self, value: typing.Optional[typing.Sequence[typing.Sequence[builtins.float]]]) -> None:
        r"""
        ([[lower_1, upper_1], ..., [lower_nx, upper_nx]] where nx is the dimension of inputs x)
        Space search when optimizing theta GP hyperparameters
        When None the default is [1e-2, 1e1] for all components.
        Note: `Egor` may adapt these bounds automatically for high-dimensional inputs.
        """
    @property
    def n_start(self) -> builtins.int:
        r"""
        (int >= 0)
        Number of internal GP hyperparameters optimization restarts (multistart).
        When zero, optimization is disabled and theta init value is used as is.
        Not to be confused with `Egor(n_start=...)`, the infill criterion optimization multistart.
        """
    @n_start.setter
    def n_start(self, value: builtins.int) -> None:
        r"""
        (int >= 0)
        Number of internal GP hyperparameters optimization restarts (multistart).
        When zero, optimization is disabled and theta init value is used as is.
        Not to be confused with `Egor(n_start=...)`, the infill criterion optimization multistart.
        """
    @property
    def max_eval(self) -> builtins.int:
        r"""
        (int >= 0)
        Max number of likelihood evaluations of each GP hyperparameters optimization start.
        This is an upper limit: each start gets clamp(10 * nx, 25, max_eval) evaluations.
        Not to be confused with `Egor.minimize(max_iters=...)`, the optimization iteration budget.
        """
    @max_eval.setter
    def max_eval(self, value: builtins.int) -> None:
        r"""
        (int >= 0)
        Max number of likelihood evaluations of each GP hyperparameters optimization start.
        This is an upper limit: each start gets clamp(10 * nx, 25, max_eval) evaluations.
        Not to be confused with `Egor.minimize(max_iters=...)`, the optimization iteration budget.
        """
    def __new__(cls, regr_spec: builtins.int = 1, corr_spec: builtins.int = 1, kpls_dim: typing.Optional[builtins.int] = None, n_clusters: builtins.int = 1, recombination: Recombination = Recombination.HARD, theta_init: typing.Optional[typing.Sequence[builtins.float]] = None, theta_bounds: typing.Optional[typing.Sequence[typing.Sequence[builtins.float]]] = None, n_start: builtins.int = 10, max_eval: builtins.int = 50) -> GpConfig:
        r"""
        Create a new GP configuration.
        
        Parameters
        ----------
        regr_spec : int, optional
            RegressionSpec flags, an int in [1, 7] (default: RegressionSpec.CONSTANT)
        corr_spec : int, optional
            CorrelationSpec flags, an int in [1, 15] (default: CorrelationSpec.SQUARED_EXPONENTIAL)
        kpls_dim : int, optional
            Number of PLS components, 0 < kpls_dim < nx (default: None, no PLS reduction)
        n_clusters : int, optional
            Number of clusters of the mixture of experts; 0 or -n for automatic selection (default: 1)
        recombination : Recombination, optional
            How the experts predictions are recombined (default: Recombination.HARD)
        theta_init : list of float, optional
            Initial guess for GP theta hyperparameters (default: None, 1e-1 for all components)
        theta_bounds : list of [float, float], optional
            Search space of GP theta hyperparameters (default: None, [1e-2, 1e1] for all components)
        n_start : int, optional
            Number of GP hyperparameters optimization restarts, 0 to disable optimization (default: 10).
            Not to be confused with `Egor(n_start=...)`, the infill criterion optimization multistart.
        max_eval : int, optional
            Max number of likelihood evaluations of each GP hyperparameters optimization start (default: 50).
            Upper limit: each start gets clamp(10 * nx, 25, max_eval) evaluations.
        
        Returns
        -------
        GpConfig
            A new GP configuration object
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class GpMix:
    r"""
    Gaussian processes mixture builder
    
    Parameters
    ----------
    xspecs : list of XSpec, list of [lower, upper] or None
        Specifications of the nx components of the input x (eg. len(xspecs) == nx),
        with XSpec(xtype=FLOAT|INT|ORD|ENUM, xlimits=[<f(xtype)>] or tags=[strings]).
        Depending on the x type we get the following for xlimits:
    
        * when FLOAT: xlimits is [float lower_bound, float upper_bound],
        * when INT: xlimits is [int lower_bound, int upper_bound],
        * when ORD: xlimits is [float_1, float_2, ..., float_n],
        * when ENUM: xlimits is just the int size of the enumeration otherwise a list of tags is specified
          (eg xlimits=[3] or tags=["red", "green", "blue"], tags are there for documentation purpose but
          tags specific values themselves are not used only indices in the enum are used hence
          we can just specify the size of the enum, xlimits=[3]).
    
        When None, inputs are expected to be floats and no input space restriction is applied
        (ie. xlimits is [-inf, inf] for all components).
    regr_spec : int
        RegressionSpec flags, an int in [1, 7]. Specification of regression models used in mixture.
        Can be RegressionSpec.CONSTANT (1), RegressionSpec.LINEAR (2), RegressionSpec.QUADRATIC (4) or
        any bit-wise union of these values (e.g. RegressionSpec.CONSTANT | RegressionSpec.LINEAR)
    corr_spec : int
        CorrelationSpec flags, an int in [1, 15]. Specification of correlation models used in mixture.
        Can be CorrelationSpec.SQUARED_EXPONENTIAL (1), CorrelationSpec.ABSOLUTE_EXPONENTIAL (2),
        CorrelationSpec.MATERN32 (4), CorrelationSpec.MATERN52 (8) or
        any bit-wise union of these values (e.g. CorrelationSpec.MATERN32 | CorrelationSpec.MATERN52)
    kpls_dim : int, optional
        Number of components to be used when PLS projection is used (a.k.a KPLS method), 0 < kpls_dim < nx.
        This is used to address high-dimensional problems typically when nx > 9.
    n_clusters : int
        Number of clusters used by the mixture of surrogate experts (default is 1).
        When set to 0, the number of cluster is determined automatically and refreshed every
        10-points addition (should say 'tentative addition' because addition may fail for some points
        but it is counted anyway).
        When set to negative number -n, the number of clusters is determined automatically in [1, n]
        this is used to limit the number of trials hence the execution time.
    recombination : Recombination
        Specify how the various experts predictions are recombined (default is Recombination.HARD)
    
        * SMOOTH: prediction is a combination of experts prediction wrt their responsibilities,
          the heaviside factor which controls steepness of the change between experts regions is optimized
          to get best mixture quality.
        * HARD: prediction is taken from the expert with highest responsibility
          resulting in a model with discontinuities.
    theta_init : list of float, optional
        Initial guess for GP theta hyperparameters, one value per input component.
        When None the default is 1e-1 for all components
    theta_bounds : list of [float, float], optional
        Search space [[lower_1, upper_1], ..., [lower_nx, upper_nx]] when optimizing theta GP hyperparameters.
        When None the default is [1e-2, 1e1] for all components.
    n_start : int >= 0
        Number of internal GP hyperparameters optimization restarts (multistart).
        When zero, optimization is disabled and theta init value is used as is.
    max_eval : int >= 0
        Max number of likelihood evaluations of each GP hyperparameters optimization start.
        This is an upper limit: each start gets clamp(10 * nx, 25, max_eval) evaluations.
    seed : int >= 0, optional
        Random generator seed to allow computation reproducibility.
        Unlike `Egor` where seed is given to `minimize()`, it is given here at construction.
    verbose : Verbose or int in [0, 4], optional
        Optional verbose level to control logging output (default is 0)
        Used mainly for debugging and development purposes.
        Unlike `Egor` where verbose is given to `minimize()`, it is given here at construction.
    
    Returns
    -------
    GpMix
        A builder which can be fitted to data to get a Gpx object (a trained Gaussian processes mixture)
    """
    def __new__(cls, xspecs: typing.Sequence[XSpec] | typing.Sequence[typing.Sequence[builtins.float]] | numpy.typing.NDArray[numpy.float64] | None = None, regr_spec: builtins.int = 1, corr_spec: builtins.int = 1, kpls_dim: typing.Optional[builtins.int] = None, n_clusters: builtins.int = 1, recombination: Recombination = Recombination.HARD, theta_init: typing.Optional[typing.Sequence[builtins.float]] = None, theta_bounds: typing.Optional[typing.Sequence[typing.Sequence[builtins.float]]] = None, n_start: builtins.int = 10, max_eval: builtins.int = 50, seed: typing.Optional[builtins.int] = None, verbose: Verbose | builtins.int | None = None) -> GpMix: ...
    def fit(self, xt: numpy.typing.NDArray[numpy.float64], yt: numpy.typing.NDArray[numpy.float64]) -> Gpx:
        r"""
        Fit the parameters of the model using the training dataset to build a trained model
        
        Parameters
        ----------
        xt : array[nsamples, nx] or array[nsamples] when nx == 1
            input samples
        yt : array[nsamples] or array[nsamples, 1]
            output samples
        
        Returns
        -------
        Gpx
            the fitted Gaussian process mixture
        """

@typing.final
class Gpx:
    r"""
    A trained Gaussian processes mixture
    """
    @staticmethod
    def builder(xspecs: typing.Sequence[XSpec] | typing.Sequence[typing.Sequence[builtins.float]] | numpy.typing.NDArray[numpy.float64] | None = None, regr_spec: builtins.int = 1, corr_spec: builtins.int = 1, kpls_dim: typing.Optional[builtins.int] = None, n_clusters: builtins.int = 1, recombination: Recombination = Recombination.HARD, theta_init: typing.Optional[typing.Sequence[builtins.float]] = None, theta_bounds: typing.Optional[typing.Sequence[typing.Sequence[builtins.float]]] = None, n_start: builtins.int = 10, max_eval: builtins.int = 50, seed: typing.Optional[builtins.int] = None, verbose: Verbose | builtins.int | None = None) -> GpMix:
        r"""
        Get Gaussian processes mixture builder aka `GpMix`
        
        See `GpMix` constructor for parameters description
        """
    def __repr__(self) -> builtins.str:
        r"""
        Returns the String representation from serde json serializer
        """
    def __str__(self) -> builtins.str:
        r"""
        Returns a String informal representation
        """
    def save(self, filename: builtins.str) -> builtins.bool:
        r"""
        Save Gaussian processes mixture in a file.
        If the filename has .json JSON human readable format is used
        otherwise an optimized binary format is used.
        
        Parameters
        ----------
        filename : str
            file path with .json or .bin extension
        
        Returns
        -------
        bool
            True when save succeeds
        
        Raises
        ------
        OSError or ValueError
            when the model can not be saved
        """
    @staticmethod
    def load(filename: builtins.str) -> Gpx:
        r"""
        Load Gaussian processes mixture from file.
        
        Parameters
        ----------
        filename : str
            .json or .bin file path generated by saving a trained model
        
        Returns
        -------
        Gpx
            the loaded model
        
        Raises
        ------
        OSError or ValueError
            when the model can not be loaded
        """
    def predict(self, x: numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Predict output values at nsamples points.
        
        Parameters
        ----------
        x : array[nsamples, nx] or array[nsamples] when nx == 1
            input values
        
        Returns
        -------
        array[nsamples]
            the output values at the nsamples x points
        """
    def predict_var(self, x: numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Predict variances at nsamples points.
        
        Parameters
        ----------
        x : array[nsamples, nx] or array[nsamples] when nx == 1
            input values
        
        Returns
        -------
        array[nsamples]
            the variances of the output values at the nsamples x points
        """
    def predict_gradients(self, x: numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Predict surrogate output derivatives at nsamples points.
        
        Parameters
        ----------
        x : array[nsamples, nx] or array[nsamples] when nx == 1
            input values
        
        Returns
        -------
        array[nsamples, nx]
            the output derivatives wrt inputs at the nsamples x points.
            The ith column is the partial derivative wrt the ith component of x.
        """
    def predict_var_gradients(self, x: numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Predict variance derivatives at nsamples points.
        
        Parameters
        ----------
        x : array[nsamples, nx] or array[nsamples] when nx == 1
            input values
        
        Returns
        -------
        array[nsamples, nx]
            the variance derivatives wrt inputs at the nsamples x points.
            The ith column is the partial derivative wrt the ith component of x.
        """
    def sample(self, x: numpy.typing.NDArray[numpy.float64], n_traj: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Sample gaussian process trajectories.
        
        Parameters
        ----------
        x : array[nsamples, nx] or array[nsamples] when nx == 1
            locations of the sampled trajectories
        n_traj : int
            number of trajectories to generate
        
        Returns
        -------
        array[nsamples, n_traj]
            the trajectories
        """
    def dims(self) -> tuple[builtins.int, builtins.int]:
        r"""
        Get the input and output dimensions of the surrogate
        
        Returns
        -------
        tuple[int, int]
            the couple (nx, ny)
        """
    def update(self, x_new: numpy.typing.NDArray[numpy.float64], y_new: numpy.typing.NDArray[numpy.float64]) -> Gpx:
        r"""
        Update the mixture of experts with new data points.
        
        For single-expert mixtures, uses efficient GP update with Cholesky rank-1 updates.
        For multi-expert mixtures, assigns new points to clusters and refits experts with fixed theta.
        
        Parameters
        ----------
        x_new : array[n_new, nx] or array[n_new] when nx == 1
            new input data points
        y_new : array[n_new] or array[n_new, 1]
            new output data values
        
        Returns
        -------
        Gpx
            a new Gpx instance updated with the new data
        
        Examples
        --------
        >>> import egobox as egx
        >>> import numpy as np
        >>> gpx = egx.Gpx.builder().fit(np.array([[0.0], [1.0]]), np.array([0.0, 1.0]))
        >>> gpx_updated = gpx.update(np.array([[2.0]]), np.array([1.5]))
        """
    def training_data(self) -> tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64]]:
        r"""
        Get the nt training data points used to fit the surrogate
        
        Returns
        -------
        tuple[array[nt, nx], array[nt]]
            the couple (xt, yt)
        """
    def thetas(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Get optimized thetas hyperparameters (ie once GP experts are fitted)
        
        Returns
        -------
        array[n_clusters, nx or kpls_dim]
            thetas of each expert
        """
    def variances(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Get GP expert variance (ie posterior GP variance)
        
        Returns
        -------
        array[n_clusters]
            variance of each expert
        """
    def likelihoods(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Get reduced likelihood values obtained when fitting the GP experts
        
        May be used to compare various parameterizations
        
        Returns
        -------
        array[n_clusters]
            likelihood of each expert
        """

@typing.final
class OptimResult:
    r"""
    OptimResult contains the results of a run of the optimization algorithm,
    including the optimal point and value found, the DOE points and values which
    includes initial points and the optimization history.
    """
    @property
    def x_opt(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Optimal x point found by the optimization algorithm
        """
    @property
    def y_opt(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Optimal y point found by the optimization algorithm
        """
    @property
    def x_doe(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        DOE x points, including initial points and optimization history
        """
    @property
    def y_doe(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        DOE y points, including initial points and optimization history
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class QEiConfig:
    r"""
    Configuration for parallel (qEI) infill criterion evaluation.
    
    The q-parallel configuration allows for evaluating multiple points
    in parallel during each EGO iteration, which can significantly speed up
    optimization when function evaluations can be performed in parallel.
    
    Parameters
    ----------
    
    batch : int
        Number of points to evaluate in parallel at each iteration.
        When set to 1, standard sequential EGO is used.
    
    strategy : QEiStrategy
        Strategy for selecting multiple points:
        * KB (Kriging Believer): Uses the GP mean prediction as a pseudo-observation
        * KBLB (Kriging Believer Lower Bound): Uses GP mean - std as pseudo-observation
        * KBUB (Kriging Believer Upper Bound): Uses GP mean + std as pseudo-observation
        * CLMIN (Constant Liar Minimum): Uses the current best value as pseudo-observation
    
    optmod : int
        Optimization modulo: interval between two GP hyperparameter optimizations
        when computing the q points of a batch. For example, with optmod=2,
        hyperparameters are optimized every 2 points, otherwise they are kept as is.
    """
    @property
    def batch(self) -> builtins.int:
        r"""
        Number of points to evaluate in parallel
        """
    @batch.setter
    def batch(self, value: builtins.int) -> None:
        r"""
        Number of points to evaluate in parallel
        """
    @property
    def strategy(self) -> QEiStrategy:
        r"""
        Strategy for selecting multiple points in parallel
        """
    @strategy.setter
    def strategy(self, value: QEiStrategy) -> None:
        r"""
        Strategy for selecting multiple points in parallel
        """
    @property
    def optmod(self) -> builtins.int:
        r"""
        Interval between hyperparameter optimizations
        """
    @optmod.setter
    def optmod(self, value: builtins.int) -> None:
        r"""
        Interval between hyperparameter optimizations
        """
    def __new__(cls, batch: builtins.int = 1, strategy: QEiStrategy = QEiStrategy.KB, optmod: builtins.int = 1) -> QEiConfig:
        r"""
        Create a new parallel evaluation configuration.
        
        Parameters
        ----------
        
        batch : int, optional
            Number of points to evaluate in parallel (default: 1)
        
        strategy : QEiStrategy, optional
            Strategy for parallel point selection (default: QEiStrategy.KB)
        
        optmod : int, optional
            Interval between hyperparameter optimizations (default: 1)
        
        Returns
        -------
        
        QEiConfig
            A new parallel evaluation configuration object
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RegressionSpec:
    r"""
    RegressionSpec is a bitfield that specifies which regression terms to include in the model.
    """
    ALL: builtins.int = 7
    CONSTANT: builtins.int = 1
    LINEAR: builtins.int = 2
    QUADRATIC: builtins.int = 4

@typing.final
class RunInfo:
    r"""
    RunInfo contains information about a single run of the optimization algorithm,
    the name of the function being optimized and the run number (useful for logging and saving results).
    This is given by the user when calling the optimization function and is used for logging and saving results.
    This information is also returned in the RunStatus to allow the user to correlate the results
    with the function and run number.
    """
    @property
    def fname(self) -> builtins.str:
        r"""
        A name for the function being optimized, used for logging and saving results
        """
    @fname.setter
    def fname(self, value: builtins.str) -> None:
        r"""
        A name for the function being optimized, used for logging and saving results
        """
    @property
    def num(self) -> builtins.int:
        r"""
        A number for the run, used for logging and saving results
        """
    @num.setter
    def num(self, value: builtins.int) -> None:
        r"""
        A number for the run, used for logging and saving results
        """
    def __new__(cls, fname: builtins.str = 'objective_function', num: builtins.int = 1) -> RunInfo: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class RunStatus:
    r"""
    RunStatus contains information about the status of a run of the optimization algorithm
    It is returned by the optimizer together with the optimization results.
    """
    @property
    def info(self) -> RunInfo:
        r"""
        Information about the run, provided by the user when calling the optimization function
        """
    @property
    def exit(self) -> ExitStatus:
        r"""
        Exit status of the optimization algorithm, which indicates the reason for termination of the algorithm
        """
    @property
    def init_doe_size(self) -> builtins.int:
        r"""
        Number of points in the initial DOE, which is useful to correlate with the results and understand the behavior of the optimization algorithm
        """
    @property
    def best_iter(self) -> builtins.int:
        r"""
        Best iteration of the optimization algorithm, allows to retrieve optimal values in the optimization history
        """
    @property
    def total_iters(self) -> builtins.int:
        r"""
        Total number of iterations performed by the optimization algorithm
        """
    @property
    def elapsed_time(self) -> builtins.float:
        r"""
        Elapsed time of the optimization algorithm in seconds
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class SparseGpMix:
    r"""
    Sparse Gaussian process builder
    
    Inducing points are required: give either their number `nz` or their locations `z`.
    
    Parameters
    ----------
    corr_spec : int
        CorrelationSpec flags, an int in [1, 15]. Specification of correlation models.
        Can be CorrelationSpec.SQUARED_EXPONENTIAL (1), CorrelationSpec.ABSOLUTE_EXPONENTIAL (2),
        CorrelationSpec.MATERN32 (4), CorrelationSpec.MATERN52 (8) or
        any bit-wise union of these values (e.g. CorrelationSpec.MATERN32 | CorrelationSpec.MATERN52)
    theta_init : list of float, optional
        Initial guess for GP theta hyperparameters, one value per input component.
        When None the default is 1e-1 for all components
    theta_bounds : list of [float, float], optional
        Search space [[lower_1, upper_1], ..., [lower_nx, upper_nx]] when optimizing theta GP hyperparameters.
        When None the default is [1e-2, 1e1] for all components.
    kpls_dim : int, optional
        Number of components to be used when PLS projection is used (a.k.a KPLS method), 0 < kpls_dim < nx.
        This is used to address high-dimensional problems typically when nx > 9.
    n_start : int >= 0
        Number of internal GP hyperparameters optimization restarts (multistart)
    nz : int, optional
        Number of inducing points, randomly picked among the training inputs.
        Used when `z` is not given.
    z : array[nz, nx], optional
        Locations of the inducing points. Takes precedence over `nz`.
    method : SparseMethod
        Sparse method to be used (default is SparseMethod.FITC)
    seed : int >= 0, optional
        Random generator seed to allow computation reproducibility.
    verbose : Verbose or int in [0, 4], optional
        Optional verbose level to control logging output (default is 0)
        Used mainly for debugging and development purposes
    
    Returns
    -------
    SparseGpMix
        A builder which can be fitted to data to get a SparseGpx object (a trained sparse Gaussian process)
    """
    def __new__(cls, corr_spec: builtins.int = 1, theta_init: typing.Optional[typing.Sequence[builtins.float]] = None, theta_bounds: typing.Optional[typing.Sequence[typing.Sequence[builtins.float]]] = None, kpls_dim: typing.Optional[builtins.int] = None, n_start: builtins.int = 10, nz: typing.Optional[builtins.int] = None, z: typing.Optional[numpy.typing.NDArray[numpy.float64]] = None, method: SparseMethod = SparseMethod.FITC, seed: typing.Optional[builtins.int] = None, verbose: Verbose | builtins.int | None = None) -> SparseGpMix: ...
    def fit(self, xt: numpy.typing.NDArray[numpy.float64], yt: numpy.typing.NDArray[numpy.float64]) -> SparseGpx:
        r"""
        Fit the parameters of the model using the training dataset to build a trained model
        
        Parameters
        ----------
        xt : array[nsamples, nx] or array[nsamples] when nx == 1
            input samples
        yt : array[nsamples] or array[nsamples, 1]
            output samples
        
        Returns
        -------
        SparseGpx
            the fitted sparse Gaussian process
        """

@typing.final
class SparseGpx:
    r"""
    A trained sparse Gaussian process
    
    Unlike `Gpx`, it has no `update` method: sparse GPs have to be refitted with the new data.
    """
    @staticmethod
    def builder(corr_spec: builtins.int = 1, theta_init: typing.Optional[typing.Sequence[builtins.float]] = None, theta_bounds: typing.Optional[typing.Sequence[typing.Sequence[builtins.float]]] = None, kpls_dim: typing.Optional[builtins.int] = None, n_start: builtins.int = 10, nz: typing.Optional[builtins.int] = None, z: typing.Optional[numpy.typing.NDArray[numpy.float64]] = None, method: SparseMethod = SparseMethod.FITC, seed: typing.Optional[builtins.int] = None, verbose: Verbose | builtins.int | None = None) -> SparseGpMix:
        r"""
        Get sparse Gaussian process builder aka `SparseGpMix`
        
        See `SparseGpMix` constructor for parameters description
        """
    def __repr__(self) -> builtins.str:
        r"""
        Returns the String representation from serde json serializer
        """
    def __str__(self) -> builtins.str:
        r"""
        Returns a String informal representation
        """
    def save(self, filename: builtins.str) -> builtins.bool:
        r"""
        Save Gaussian processes mixture in a file.
        If the filename has .json JSON human readable format is used
        otherwise an optimized binary format is used.
        
        Parameters
        ----------
        filename : str
            file path with .json or .bin extension
        
        Returns
        -------
        bool
            True when save succeeds
        
        Raises
        ------
        OSError or ValueError
            when the model can not be saved
        """
    @staticmethod
    def load(filename: builtins.str) -> SparseGpx:
        r"""
        Load Gaussian processes mixture from file.
        
        Parameters
        ----------
        filename : str
            .json or .bin file path generated by saving a trained model
        
        Returns
        -------
        SparseGpx
            the loaded model
        
        Raises
        ------
        OSError or ValueError
            when the model can not be loaded
        """
    def predict(self, x: numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Predict output values at nsamples points.
        
        Parameters
        ----------
        x : array[nsamples, nx] or array[nsamples] when nx == 1
            input values
        
        Returns
        -------
        array[nsamples]
            the output values at the nsamples x points
        """
    def predict_var(self, x: numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Predict variances at nsamples points.
        
        Parameters
        ----------
        x : array[nsamples, nx] or array[nsamples] when nx == 1
            input values
        
        Returns
        -------
        array[nsamples]
            the variances of the output values at the nsamples x points
        """
    def predict_gradients(self, x: numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Predict surrogate output derivatives at nsamples points.
        
        Implementation note: central finite difference technique
        on `predict()` function is used which may be subject to numerical issues
        
        Parameters
        ----------
        x : array[nsamples, nx] or array[nsamples] when nx == 1
            input values
        
        Returns
        -------
        array[nsamples, nx]
            the output derivatives wrt inputs at the nsamples x points.
            The ith column is the partial derivative wrt the ith component of x.
        """
    def predict_var_gradients(self, x: numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Predict variance derivatives at nsamples points.
        
        Implementation note: central finite difference technique
        on `predict_var()` function is used which may be subject to numerical issues
        
        Parameters
        ----------
        x : array[nsamples, nx] or array[nsamples] when nx == 1
            input values
        
        Returns
        -------
        array[nsamples, nx]
            the variance derivatives wrt inputs at the nsamples x points.
            The ith column is the partial derivative wrt the ith component of x.
        """
    def sample(self, x: numpy.typing.NDArray[numpy.float64], n_traj: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Sample gaussian process trajectories.
        
        Parameters
        ----------
        x : array[nsamples, nx] or array[nsamples] when nx == 1
            locations of the sampled trajectories
        n_traj : int
            number of trajectories to generate
        
        Returns
        -------
        array[nsamples, n_traj]
            the trajectories
        """
    def dims(self) -> tuple[builtins.int, builtins.int]:
        r"""
        Get the input and output dimensions of the surrogate
        
        Returns
        -------
        tuple[int, int]
            the couple (nx, ny)
        """
    def training_data(self) -> tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64]]:
        r"""
        Get the nt training data points used to fit the surrogate
        
        Returns
        -------
        tuple[array[nt, nx], array[nt]]
            the couple (xt, yt)
        """
    def thetas(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Get optimized thetas hyperparameters (ie once GP experts are fitted)
        
        Returns
        -------
        array[n_clusters, nx or kpls_dim]
            thetas of each expert
        """
    def variances(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Get GP expert variance (ie posterior GP variance)
        
        Returns
        -------
        array[n_clusters]
            variance of each expert
        """
    def likelihoods(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Get reduced likelihood values obtained when fitting the GP experts
        
        May be used to compare various parameterizations
        
        Returns
        -------
        array[n_clusters]
            likelihood of each expert
        """

@typing.final
class TregoConfig:
    r"""
    Trust region configuration for EGO optimization.
    
    The TREGO algorithm enhances the Efficient Global Optimization (EGO)
    by incorporating a trust region strategy to improve local convergence.
    
    Parameters
    ----------
    n_gl_steps : (int, int)
        Number of global and local steps (gl): a tuple specifying the number of
        global and local optimization steps as (n_global_steps, n_local_steps).
    d : tuple of float
        Trust region distance (radius) bounds as (dmin, dmax). The trust region radius
        is constrained between these values.
    alpha : float
        Factor used within the trust region acceptance criteria defined as:
        rho(sigma) = alpha * sigma * sigma
    beta : float
        Trust region contraction factor in ]0., 1.[
    sigma0 : float
        Initial trust region radius.
    """
    @property
    def n_gl_steps(self) -> tuple[builtins.int, builtins.int]:
        r"""
        Number of global and local optimization steps (n_global_steps, n_local_steps)
        """
    @n_gl_steps.setter
    def n_gl_steps(self, value: tuple[builtins.int, builtins.int]) -> None:
        r"""
        Number of global and local optimization steps (n_global_steps, n_local_steps)
        """
    @property
    def d(self) -> tuple[builtins.float, builtins.float]:
        r"""
        Trust region size bounds (dmin, dmax) with 0 < dmin < dmax
        """
    @d.setter
    def d(self, value: tuple[builtins.float, builtins.float]) -> None:
        r"""
        Trust region size bounds (dmin, dmax) with 0 < dmin < dmax
        """
    @property
    def alpha(self) -> builtins.float:
        r"""
        Threshold ratio for iteration acceptance used in trust region criteria
        rho(sigma) = alpha * sigma * sigma
        """
    @alpha.setter
    def alpha(self, value: builtins.float) -> None:
        r"""
        Threshold ratio for iteration acceptance used in trust region criteria
        rho(sigma) = alpha * sigma * sigma
        """
    @property
    def beta(self) -> builtins.float:
        r"""
        Trust region contraction factor
        """
    @beta.setter
    def beta(self, value: builtins.float) -> None:
        r"""
        Trust region contraction factor
        """
    @property
    def sigma0(self) -> builtins.float:
        r"""
        Initial trust region radius
        """
    @sigma0.setter
    def sigma0(self, value: builtins.float) -> None:
        r"""
        Initial trust region radius
        """
    def __new__(cls, n_gl_steps: tuple[builtins.int, builtins.int] = (1, 4), d: tuple[builtins.float, builtins.float] = (1e-06, 1.0), alpha: builtins.float = 1.0, beta: builtins.float = 0.9, sigma0: builtins.float = 0.1) -> TregoConfig:
        r"""
        Create a new TReGO configuration.
        
        Parameters
        ----------
        n_gl_steps : (int, int), optional
            Number of global/local steps (default: (1, 4))
        d : tuple of float, optional
            Trust region size bounds (default: (1e-6, 1.0))
        alpha : float, optional
            Threshold ratio for iteration acceptance (default: 1.0)
        beta : float, optional
            Trust region contraction factor (default: 0.9)
        sigma0 : float, optional
            Initial trust region radius (default: 0.1)
        
        Returns
        -------
        TregoConfig
            A new TREGO configuration object
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class XSpec:
    r"""
    XSpec specifies the type and limits of the input variables (aka design space).
    """
    @property
    def xtype(self) -> XType: ...
    @property
    def xlimits(self) -> builtins.list[builtins.float]: ...
    @property
    def tags(self) -> builtins.list[builtins.str]: ...
    def __new__(cls, xtype: XType, xlimits: typing.Sequence[builtins.float] = [], tags: typing.Sequence[builtins.str] = []) -> XSpec: ...

@typing.final
class ConstraintStrategy(enum.Enum):
    r"""
    ConstraintStrategy specifies the strategy to use for handling constraints in infill optimization.
    """
    MC = ...
    r"""
    Mean Constraint (MC): the mean of the GP is used to evaluate the constraint,
    which is equivalent to ignoring the uncertainty on the constraint
    """
    UTB = ...
    r"""
    Upper Trust Bound (UTB): the upper trust bound of the GP is used to evaluate the constraint,
    which takes into account the uncertainty on the constraint
    """

@typing.final
class ExitStatus(enum.Enum):
    r"""
    ExitStatus specifies the reason for the termination of the optimization algorithm.
    """
    MAX_ITERS_REACHED = ...
    r"""
    Reached maximum number of iterations
    """
    TARGET_COST_REACHED = ...
    r"""
    Reached target cost function value
    """
    INTERRUPT = ...
    r"""
    Algorithm manually interrupted with SIGINT (Ctrl+C), SIGTERM or SIGHUP
    """
    SOLVER_CONVERGED = ...
    r"""
    Algorithm picked the same point twice. We consider it is converged.
    """
    TIMEOUT = ...
    r"""
    Timeout reached
    """
    UNEXPECTED_EXIT = ...
    r"""
    Solver unexpected exit. See logs for details.
    """
    OBJECTIVE_FUNCTION_ERROR = ...
    r"""
    Objective function returned an error. See logs for details.
    """

@typing.final
class FailsafeStrategy(enum.Enum):
    r"""
    FailsafeStrategy specifies the strategy to use for handling failures during infill optimization.
    """
    REJECTION = ...
    r"""
    The point is ignored, the optimization continues but may fail to explore
    another region of the search space
    """
    IMPUTATION = ...
    r"""
    The point is added to the DOE with a penalized value, which allows
    the optimization to continue exploring other regions of the search space
    """
    VIABILITY = ...
    r"""
    The viability of the point is modeled with a surrogate, which allows the optimization
    to learn which regions of the search space are more likely to fail and avoid them in the future
    """

@typing.final
class FeasibleInfillStrategy(enum.Enum):
    r"""
    FeasibleInfillStrategy activates the Expected Feasible Improvement (EFI) to handle hidden constraints,
    i.e. points where the objective function fails (returns NaN or raises).
    The infill criterion is weighted by the probability of viability given by a surrogate trained
    on successful and failed points, see Tfaily et al. (2024).
    This is independent of `Egor(cstr_infill=True)` which weights the criterion by the probability
    of feasibility of the explicit constraints (`n_cstr`), both can be used together.
    """
    NONE = ...
    r"""
    Do not use feasibility information
    """
    EFI_P = ...
    r"""
    EFI with Probability (EFI_P): the criterion is weighted by the probability of viability
    """
    EFI_FE = ...
    r"""
    EFI Feasibility Enhanced (EFI_FE): the criterion is weighted by the probability of viability
    to the power 0.3, which is more exploratory than EFI_P
    """

@typing.final
class InfillOptimizer(enum.Enum):
    r"""
    InfillOptimizer specifies the optimization algorithm to use for infill optimization.
    """
    COBYLA = ...
    r"""
    Gradient free optimization algorithm that uses a simplex of n+1 points for n-dimensional optimization
    """
    SLSQP = ...
    r"""
    Gradient based optimization algorithm that uses a quasi-Newton method to optimize the acquisition function
    """

@typing.final
class InfillStrategy(enum.Enum):
    r"""
    InfillStrategy specifies the acquisition function to use for infill optimization.
    """
    EI = ...
    r"""
    Expected Improvement
    see Mockus et al. (1978) "The application of Bayesian methods for seeking the extremum"
    """
    WB2 = ...
    r"""
    Watson and Barnes 2nd criterion (WB2): EI shifted by the GP mean,
    easier to optimize than EI but may not explore as much as EI
    see Watson and Barnes (1995) "Infill sampling criteria to locate extremes"
    """
    WB2S = ...
    r"""
    Scaled version of WB2 (WB2S) to improve exploration
    """
    LOG_EI = ...
    r"""
    Logarithm of Expected Improvement (LogEI)
    see Ament et al. (2023) "Unexpected Improvements to Expected Improvement for Bayesian Optimization"
    """

@typing.final
class QEiStrategy(enum.Enum):
    r"""
    QEiStrategy specifies how the points of a qEI batch are selected: after each selected point,
    the GP is updated with a virtual value given by the strategy, then the next point is selected.
    qEI is the multi-point extension of EI, see Chevalier and Ginsbourger (2013)
    "Fast Computation of the Multi-Points Expected Improvement with Applications in Batch Selection"
    """
    KB = ...
    r"""
    Kriging Believer (KB), the next point is added to the GP with its predicted mean value,
    which is equivalent to assuming that the prediction is perfect
    """
    KBLB = ...
    r"""
    Kriging Believer Lower Bound (KBLB), the next point is added to the GP with
    its predicted mean value minus a multiple of the predicted standard deviation,
    which is equivalent to assuming that the prediction is pessimistic
    """
    KBUB = ...
    r"""
    Kriging Believer Upper Bound (KBUB), the next point is added to the GP with
    its predicted mean value plus a multiple of the predicted standard deviation,
    which is equivalent to assuming that the prediction is optimistic
    """
    CLMIN = ...
    r"""
    Constant Liar Minimum (CLMIN), the next point is added to the GP by using the current minimum
    value observed in the DOE, which is equivalent to assuming that
    the prediction is the current best value
    """

@typing.final
class Recombination(enum.Enum):
    HARD = ...
    r"""
    Prediction is taken from the expert with highest responsibility,
    resulting in a model with discontinuities
    """
    SMOOTH = ...
    r"""
    Prediction is a combination of experts predictions wrt their responsibilities,
    an optional heaviside factor might be used to control steepness of the change between
    experts regions.
    """

@typing.final
class Sampling(enum.Enum):
    r"""
    Sampling specifies the method used to generate samples, see `sampling()`.
    """
    LHS = ...
    r"""
    Optimized Latin Hypercube Sampling: sample locations are optimized using the
    Enhanced Stochastic Evolutionary algorithm (ESE), see Jin et al. (2005)
    "An efficient algorithm for constructing optimal design of computer experiments"
    """
    FULL_FACTORIAL = ...
    r"""
    Full factorial sampling: points of a regular grid
    """
    RANDOM = ...
    r"""
    Uniform random sampling
    """
    LHS_CLASSIC = ...
    r"""
    Classic LHS: each sample is chosen randomly within its latin hypercube interval
    """
    LHS_CENTERED = ...
    r"""
    Centered LHS: each sample is the middle of its latin hypercube interval
    """
    LHS_MAXIMIN = ...
    r"""
    Maximin LHS: the minimal distance between samples is maximized
    """
    LHS_CENTERED_MAXIMIN = ...
    r"""
    Centered maximin LHS: centered samples with the minimal distance between samples maximized
    """

@typing.final
class SparseMethod(enum.Enum):
    r"""
    SparseMethod specifies the method to use for sparse Gaussian process regression.
    See "Sparse Gaussian Process Regression for Big Data" by V. Vanhatalo, J. Riihimäki, J. Hartikainen, and A. Vehtari (2010)
    """
    FITC = ...
    r"""
    FITC (Fully Independent Training Conditional) method, which uses a subset of the training data to make predictions, resulting in a faster but less accurate model
    """
    VFE = ...
    r"""
    VFE (Variational Free Energy) method, which uses a variational approach to approximate the posterior, resulting in a more accurate but slower model
    """

@typing.final
class Verbose(enum.Enum):
    r"""
    Verbose specifies the level of verbosity for logging.
    """
    ERROR = ...
    WARNING = ...
    INFO = ...
    DEBUG = ...
    TRACE = ...

@typing.final
class XType(enum.Enum):
    r"""
    XType specifies the type of the input variables.
    """
    FLOAT = ...
    INT = ...
    ORD = ...
    ENUM = ...

def lhs(xspecs: typing.Sequence[XSpec] | typing.Sequence[typing.Sequence[builtins.float]] | numpy.typing.NDArray[numpy.float64], n_samples: builtins.int, seed: typing.Optional[builtins.int] = None) -> numpy.typing.NDArray[numpy.float64]:
    r"""
    Samples generation using optimized Latin Hypercube Sampling,
    same as `sampling(Sampling.LHS, xspecs, n_samples, seed)`
    
    Parameters
    ----------
    xspecs : list of XSpec, list of [lower, upper] or array[nx, 2]
        Specifications of the nx input variables
    n_samples : int
        number of samples
    seed : int >= 0, optional
        random seed
    
    Returns
    -------
    array[n_samples, nx]
        the samples
    """

def sampling(method: Sampling, xspecs: typing.Sequence[XSpec] | typing.Sequence[typing.Sequence[builtins.float]] | numpy.typing.NDArray[numpy.float64], n_samples: builtins.int, seed: typing.Optional[builtins.int] = None) -> numpy.typing.NDArray[numpy.float64]:
    r"""
    Samples generation using given method
    
    Parameters
    ----------
    method : Sampling
        Sampling.LHS, FULL_FACTORIAL, RANDOM, LHS_CLASSIC, LHS_CENTERED,
        LHS_MAXIMIN or LHS_CENTERED_MAXIMIN. Plain LHS is the optimized (ESE) LHS.
    xspecs : list of XSpec, list of [lower, upper] or array[nx, 2]
        Specifications of the nx input variables
    n_samples : int
        number of samples
    seed : int >= 0, optional
        random seed
    
    Returns
    -------
    array[n_samples, nx]
        the samples
    """

