base_url = "https://relf.github.io/EGObox/"
title = "EGObox"
description = "Efficient Global Optimization toolbox for Rust and Python"

default_language = "en"
build_search_index = true

[search]
index_format = "elasticlunr_json"

[markdown]
external_links_target_blank = true
smart_punctuation = true
insert_anchor_links = "right"

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
header = { title = "EGObox website" }
author = "Rémi Lafage"
